// This file is autogenerated. Do not edit this code manually as changes may be lost.
// To update, go to the 'server' folder, edit the API implementation in ChangePassword.api.ts, then run 'npm run link-api .\src\api_endpoints\authentication\ChangePassword.api.ts'.

import APIRequest from "../APIRequest";

class ChangePasswordAPI extends APIRequest<
  {
    currentPassword: string;
    newPassword: string;
  },
  {
    success: boolean;
    error: string | null;
  }
> {
  constructor() {
    super({
      path: "/auth/change_password",
      method: "post",
      requireAuthentication: true,
    });
  }
}

export default ChangePasswordAPI;
