// This file is autogenerated. Do not edit this code manually as changes may be lost.
// To update, go to the 'server' folder, edit the API implementation in ChangeDisplayName.api.ts, then run 'npm run link-api .\src\api_endpoints\authentication\ChangeDisplayName.api.ts'.

import APIRequest from "../APIRequest";

class ChangeDisplayNameAPI extends APIRequest<
  {
    displayName: string;
  },
  {
    success: boolean;
    error: string | null;
    token: string | null;
  }
> {
  constructor() {
    super({
      path: "/auth/change_display_name",
      method: "post",
    });
  }
}

export default ChangeDisplayNameAPI;
