// This file is autogenerated. Do not edit this code manually as changes may be lost.
// To update, go to the 'server' folder, edit the API implementation in CreateAccount.api.ts, then run 'npm run link-api .\src\api_endpoints\authentication\CreateAccount.api.ts'.

import APIRequest from "../APIRequest";

class CreateAccountAPI extends APIRequest<
  {
    email: string;
    password: string;
    displayName: string;
  },
  {
    success: boolean;
    error: null | string;
    token: null | string;
  }
> {
  constructor() {
    super({
      path: "/auth/register",
      method: "post",
    });
  }
}

export default CreateAccountAPI;
