// This file is autogenerated. Do not edit this code manually as changes may be lost.
// To update, go to the 'server' folder, edit the API implementation in HelloCat.api.ts, then run 'npm run link-api .\src\api_endpoints\HelloCat.api.ts'.

import APIRequest from "../APIRequest";

class HelloCatAPI extends APIRequest<any, any> {
  constructor() {
    super({
      method: "get",
      path: "/cat",
      requireAuthentication: true,
      requireAnyOfPermissions: ["admin"],
    });
  }
}

export default HelloCatAPI;
