// This file is autogenerated. Do not edit this code manually as changes may be lost.
// To update, go to the 'server' folder, edit the API implementation in Login.api.ts, then run 'npm run link-api .\src\api_endpoints\authentication\Login.api.ts'.

import APIRequest from "../APIRequest";

class LoginAPI extends APIRequest<
  {
    email: string;
    password: string;
  },
  {
    success: boolean;
    error: string | null;
    token: string | null;
  }
> {
  constructor() {
    super({
      method: "post",
      path: "/auth/login",
    });
  }
}

export default LoginAPI;
