// This file is autogenerated. Do not edit this code manually as changes may be lost.
// To update, go to the 'server' folder, edit the API implementation in RunJob.api.ts, then run 'npm run link-api .\src\api_endpoints\admin\jobs\RunJob.api.ts'.

import APIRequest from "../APIRequest";

class RunJobAPI extends APIRequest<
  {
    jobName: string;
  },
  { success: boolean }
> {
  constructor() {
    super({
      path: "/admin/jobs/run",
      method: "post",
      requireAllOfPermissions: ["admin"],
    });
  }
}

export default RunJobAPI;
