// ⚠️ THIS FILE IS AUTO-GENERATED
// This file is automatically generated based on a collection created in PocketBase. Any changes made here may be lost.
// To update, edit the collection in PocketBase or apply a migration (recommended), then run `pnpm run generate-types`.

import { createPBCollectionStore } from "../lib/PBCollectionStore";

export interface TodoItem {
  id: string;
  title: string;
  completed: boolean;
  user: string[];
  created: number;
  updated: number;
}

export const useTodoItemStore = createPBCollectionStore<TodoItem>("todo_item");
